tool_env := "uv run"
python_env := "{{tool_env}} python"

default:
  @just --list

prefect:
    {{tool_env}} prefect server start

mlflow:
    {{tool_env}} mlflow server --host 127.0.0.1 --port 8080

train: mlflow
    @echo train

eval: mlflow
    @echo test

etl: prefect
    {{python_env}} src/data/main.py
